# Generated by Django 3.1.3 on 2020-11-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_published',
            new_name='date_posted',
        ),
    ]
